"""Rich distillation: deep-insight elegant problems with dual elegance ratings.

Each problem is generated by claude-opus-4-8 with HIGH-effort extended thinking:
the model first brainstorms a non-obvious crux, builds an elegant problem around
it, solves it while double-checking the integer answer, then rates BOTH the
problem's elegance and the solution's elegance (0-5). Those ratings are stored so
the dataset carries an explicit signal of "what a quality problem is".

Per-problem commits (survives interruption). Quality/diversity filters applied.
Answers are the model's self-verified values (with thinking) -- NOT yet exhaustively
Python-checked; a later verification pass should confirm correctness. Stored as
review_status=pending.

Usage: PYTHONPATH=src python scripts/distill_rich.py <N>   (after sourcing .env.local)
"""

from __future__ import annotations

import re
import sys
import uuid

from sqlmodel import select

from mathforge import db
from mathforge.distill import (
    DIVERSITY_TOPICS,
    _avoid_block,
    _rotate_target,
    is_banned_template,
    is_garbled,
    is_near_duplicate,
    token_set,
)
from mathforge.llm import LLMClient, make_anthropic_backend
from mathforge.schema import (
    DataSplit,
    Evaluation,
    Problem,
    ProblemSource,
    ReviewStatus,
    Solution,
    SolutionSource,
    statement_hash,
)

MODEL = "claude-opus-4-8"
EVALUATOR = "opus-4.8-thinking"

PROMPT = r"""You are an elite olympiad problem composer AND a rigorous solver. Use your extended thinking fully.

PHASE 1 - find a deep insight. Brainstorm several non-obvious mathematical cruxes (a surprising identity, invariant, bijection, symmetry, generating function, or reformulation). Choose ONE that a strong student would find genuinely hard to discover, yet that collapses the problem to a short clean solution once seen.

PHASE 2 - compose ONE original competition problem built on that crux:
- The final answer must be a single integer from 0 to 999 (AIME-style), unique and well-defined.
- Self-contained, unambiguous, well-posed; not a known/existing contest problem.
- Vary the mathematical object and the solving mechanism; avoid cliches. Do NOT define a polynomial P(x) and ask for a value of it.

PHASE 3 - solve it rigorously, and DOUBLE-CHECK the integer answer by recomputing it a different way inside your thinking. Make sure it is correct and lies in [0,999].

PHASE 4 - rate two things, each 0.0-5.0 (one decimal):
- problem_elegance: beauty of the PROBLEM (5 = striking, surprising, minimal setup, one deep crux; 3 = solid; 1 = routine or contrived).
- solution_elegance: beauty of the SOLUTION (5 = short and inevitable-feeling, one key idea; 1 = long case-work or heavy computation).

Target for this problem: {target}

Recently generated - produce something clearly DIFFERENT from all of these:
{avoid}

Output EXACTLY these tags and nothing else:
<statement>the full problem statement (LaTeX allowed)</statement>
<answer>the integer 0-999</answer>
<topic>Algebra | Geometry | Number Theory | Combinatorics | Precalculus</topic>
<difficulty>AoPS-style difficulty 1-10, one decimal</difficulty>
<crux>one sentence naming the key insight</crux>
<solution>a complete rigorous solution ending at the integer answer</solution>
<problem_elegance>0-5</problem_elegance>
<problem_elegance_reason>one sentence</problem_elegance_reason>
<solution_elegance>0-5</solution_elegance>
<solution_elegance_reason>one sentence</solution_elegance_reason>
"""


def _tag(name: str, text: str):
    m = re.search(rf"<{name}>\s*(.*?)\s*</{name}>", text or "", re.DOTALL | re.IGNORECASE)
    return m.group(1).strip() if m else None


def _num(raw, lo, hi):
    if raw is None:
        return None
    m = re.search(r"-?\d+(\.\d+)?", raw)
    if not m:
        return None
    v = float(m.group())
    return v if lo <= v <= hi else None


def _int_answer(raw):
    if raw is None:
        return None
    m = re.search(r"-?\d+", raw)
    if not m:
        return None
    v = int(m.group())
    return v if 0 <= v <= 999 else None


def _generate_one(client, prompt: str) -> str:
    """Issue one max-thinking generation. Returns raw text, or an __ERR__ marker."""
    try:
        return client.complete(prompt, purpose="distill-rich", effort="high").text
    except Exception as e:  # noqa: BLE001 - report and keep the pool going
        return f"__ERR__{type(e).__name__}: {e}"


def main() -> None:
    n = int(sys.argv[1]) if len(sys.argv) > 1 else 8
    # Optional second arg = number of concurrent in-flight requests. The gateway
    # serves parallel calls, so this multiplies throughput ~linearly; dedup and
    # DB writes still happen serially in the main thread, so no locks are needed.
    workers = int(sys.argv[2]) if len(sys.argv) > 2 else 1
    db.init_db()
    client = LLMClient(
        model=MODEL,
        backend=make_anthropic_backend(MODEL, effort="high", max_output_tokens=32000, timeout=600.0),
        purpose="distill-rich",
    )

    with db.session_scope() as ses:
        train_rows = ses.exec(db.training_problems_select()).all()
        seen = {p.statement_hash for p in train_rows if p.statement_hash}
        # Protect held-out items by hash without exposing their statements/cruxes
        # to the generator prompt.
        seen.update(
            h for h in ses.exec(
                select(Problem.statement_hash).where(Problem.frozen == True)  # noqa: E712
            ).all() if h
        )
        seen_sigs = [token_set(p.statement) for p in train_rows if p.statement]
        # Cross-run idea-level dedup: pull the cruxes of every problem already in
        # the DB so a fresh run knows what has been done (the lexical statement
        # filter can't catch a reworded parking/concatenation problem, but the
        # crux "rotational symmetry -> each spot equally likely" is near-identical).
        existing = train_rows
        seen_crux_sigs: list = []
        seed_avoid: list[str] = []
        for p in existing:
            crux_p = (p.provenance or {}).get("crux") or ""
            if crux_p:
                seen_crux_sigs.append(token_set(crux_p))
                seed_avoid.append(f"[{p.topic}] {crux_p}")

    # Show the model the accumulated cruxes so it steers into UNUSED territory.
    recent: list[str] = seed_avoid
    stored = 0

    def _consume(t: str, target: str, label: str) -> bool:
        """Filter/dedup/store one raw generation. Runs only in the main thread."""
        nonlocal stored
        if t.startswith("__ERR__"):
            print(f"{label} gen error: {t[7:]}", flush=True)
            return False
        stmt = _tag("statement", t)
        ans = _int_answer(_tag("answer", t))
        sol = _tag("solution", t)
        if not (stmt and sol) or ans is None:
            print(f"{label} parse fail / answer out of range", flush=True)
            return False
        if is_banned_template(stmt) or is_garbled(stmt):
            print(f"{label} banned/garbled, skipped", flush=True)
            recent.append(f"[{_tag('topic', t)}] {stmt[:100]}")
            return False
        sig = token_set(stmt)
        if is_near_duplicate(sig, seen_sigs):
            print(f"{label} near-duplicate (statement), skipped", flush=True)
            recent.append(f"[{_tag('topic', t)}] {stmt[:100]}")
            return False
        sh = statement_hash(stmt)
        if sh in seen:
            print(f"{label} duplicate, skipped", flush=True)
            return False

        topic = _tag("topic", t)
        difficulty = _num(_tag("difficulty", t), 1, 10)
        crux = _tag("crux", t) or ""
        # Idea-level dedup: cruxes are short and semantic, so a lower Jaccard
        # threshold reliably catches "same insight, different wording" dupes.
        crux_sig = token_set(crux)
        if crux and is_near_duplicate(crux_sig, seen_crux_sigs, threshold=0.55):
            print(f"{label} near-duplicate (crux), skipped :: {crux[:70]}", flush=True)
            recent.append(f"[{topic}] {crux}")
            return False
        pe = _num(_tag("problem_elegance", t), 0, 5)
        pe_reason = _tag("problem_elegance_reason", t) or ""
        se = _num(_tag("solution_elegance", t), 0, 5)
        se_reason = _tag("solution_elegance_reason", t) or ""

        seen.add(sh)
        seen_sigs.append(sig)
        if crux_sig:
            seen_crux_sigs.append(crux_sig)
        recent.append(f"[{topic}] {crux or stmt[:100]}")

        pid = f"distill-rich-{uuid.uuid4().hex[:8]}"
        with db.session_scope() as ses:
            ses.add(Problem(
                id=pid, source=ProblemSource.SYNTHETIC, statement=stmt,
                answer=str(ans), difficulty=difficulty, topic=topic,
                split=DataSplit.TRAIN, verified=None, review_status=ReviewStatus.PENDING,
                possibly_memorized=False,
                provenance={
                    "pipeline": "distill-rich", "generator_model": MODEL,
                    "thinking_effort": "high", "target": target,
                    "generated_answer": str(ans), "crux": crux,
                    "elegance": {
                        "problem": pe, "problem_reason": pe_reason,
                        "solution": se, "solution_reason": se_reason,
                        "rated_by": EVALUATOR,
                    },
                },
            ).refresh_dedup_fields())
            ses.add(Solution(problem_id=pid, text=sol, crux_insight=crux,
                             source=SolutionSource.MODEL, extractor_model=MODEL))
            if pe is not None or difficulty is not None:
                ses.add(Evaluation(
                    problem_id=pid, difficulty_score=difficulty, elegance_score=pe,
                    evaluator=EVALUATOR,
                    rationale=f"problem_elegance={pe} ({pe_reason}); solution_elegance={se} ({se_reason})"[:500]))
        stored += 1
        print(f"{label} STORED {pid} ans={ans} d={difficulty} PE={pe} SE={se} [{topic}] :: {stmt[:64]}", flush=True)
        return True

    # ------------------------------------------------------------------ driver #
    max_attempts = n * 4  # allow headroom for dedup/parse rejects
    if workers <= 1:
        i = 0
        while stored < n and i < max_attempts:
            target = _rotate_target(i, DIVERSITY_TOPICS)
            prompt = PROMPT.format(target=target, avoid=_avoid_block(recent))
            _consume(_generate_one(client, prompt), target, f"[{i + 1}]")
            i += 1
    else:
        from concurrent.futures import FIRST_COMPLETED, ThreadPoolExecutor, wait

        i = 0
        with ThreadPoolExecutor(max_workers=workers) as ex:
            inflight: dict = {}
            while stored < n and (i < max_attempts or inflight):
                # keep the pool full while we still have attempts left
                while len(inflight) < workers and i < max_attempts and stored < n:
                    target = _rotate_target(i, DIVERSITY_TOPICS)
                    prompt = PROMPT.format(target=target, avoid=_avoid_block(recent))
                    inflight[ex.submit(_generate_one, client, prompt)] = (i + 1, target)
                    i += 1
                if not inflight:
                    break
                done, _ = wait(list(inflight), return_when=FIRST_COMPLETED)
                for fut in done:
                    idx, target = inflight.pop(fut)
                    _consume(fut.result(), target, f"[{idx}]")

    print(f"done: stored {stored} rich problems", flush=True)


if __name__ == "__main__":
    main()
