"""Rich distillation: deep-insight elegant problems with dual elegance ratings.

Each problem is generated by claude-opus-4-8 with HIGH-effort extended thinking:
the model first brainstorms a non-obvious crux, builds an elegant problem around
it, solves it while double-checking the integer answer, then rates BOTH the
problem's elegance and the solution's elegance (0-5). Those ratings are stored so
the dataset carries an explicit signal of "what a quality problem is".

Per-problem commits (survives interruption). Quality/diversity filters applied.
Answers are the model's self-verified values (with thinking) -- NOT yet exhaustively
Python-checked; a later verification pass should confirm correctness. Stored as
review_status=pending.

Usage: PYTHONPATH=src python scripts/distill_rich.py <N>   (after sourcing .env.local)
"""

from __future__ import annotations

import re
import sys
import uuid

from sqlmodel import select

from mathforge import db
from mathforge.distill import (
    DIVERSITY_TOPICS,
    _avoid_block,
    _rotate_target,
    is_banned_template,
    is_garbled,
    is_near_duplicate,
    token_set,
)
from mathforge.llm import LLMClient, make_anthropic_backend
from mathforge.schema import (
    DataSplit,
    Evaluation,
    Problem,
    ProblemSource,
    ReviewStatus,
    Solution,
    SolutionSource,
    statement_hash,
)

MODEL = "claude-opus-4-8"
EVALUATOR = "opus-4.8-thinking"

PROMPT = r"""You are an elite olympiad problem composer AND a rigorous solver. Use your extended thinking fully.

PHASE 1 - find a deep insight. Brainstorm several non-obvious mathematical cruxes (a surprising identity, invariant, bijection, symmetry, generating function, or reformulation). Choose ONE that a strong student would find genuinely hard to discover, yet that collapses the problem to a short clean solution once seen.

PHASE 2 - compose ONE original competition problem built on that crux:
- The final answer must be a single integer from 0 to 999 (AIME-style), unique and well-defined.
- Self-contained, unambiguous, well-posed; not a known/existing contest problem.
- Vary the mathematical object and the solving mechanism; avoid cliches. Do NOT define a polynomial P(x) and ask for a value of it.

PHASE 3 - solve it rigorously, and DOUBLE-CHECK the integer answer by recomputing it a different way inside your thinking. Make sure it is correct and lies in [0,999].

PHASE 4 - rate two things, each 0.0-5.0 (one decimal):
- problem_elegance: beauty of the PROBLEM (5 = striking, surprising, minimal setup, one deep crux; 3 = solid; 1 = routine or contrived).
- solution_elegance: beauty of the SOLUTION (5 = short and inevitable-feeling, one key idea; 1 = long case-work or heavy computation).

Target for this problem: {target}

Recently generated - produce something clearly DIFFERENT from all of these:
{avoid}

Output EXACTLY these tags and nothing else:
<statement>the full problem statement (LaTeX allowed)</statement>
<answer>the integer 0-999</answer>
<topic>Algebra | Geometry | Number Theory | Combinatorics | Precalculus</topic>
<difficulty>AoPS-style difficulty 1-10, one decimal</difficulty>
<crux>one sentence naming the key insight</crux>
<solution>a complete rigorous solution ending at the integer answer</solution>
<problem_elegance>0-5</problem_elegance>
<problem_elegance_reason>one sentence</problem_elegance_reason>
<solution_elegance>0-5</solution_elegance>
<solution_elegance_reason>one sentence</solution_elegance_reason>
"""


def _tag(name: str, text: str):
    m = re.search(rf"<{name}>\s*(.*?)\s*</{name}>", text or "", re.DOTALL | re.IGNORECASE)
    return m.group(1).strip() if m else None


def _num(raw, lo, hi):
    if raw is None:
        return None
    m = re.search(r"-?\d+(\.\d+)?", raw)
    if not m:
        return None
    v = float(m.group())
    return v if lo <= v <= hi else None


def _int_answer(raw):
    if raw is None:
        return None
    m = re.search(r"-?\d+", raw)
    if not m:
        return None
    v = int(m.group())
    return v if 0 <= v <= 999 else None


def main() -> None:
    n = int(sys.argv[1]) if len(sys.argv) > 1 else 8
    db.init_db()
    client = LLMClient(
        model=MODEL,
        backend=make_anthropic_backend(MODEL, effort="high", max_output_tokens=32000, timeout=600.0),
        purpose="distill-rich",
    )

    with db.session_scope() as ses:
        seen = set(ses.exec(select(Problem.statement_hash)).all())
        seen_sigs = [token_set(s) for s in ses.exec(select(Problem.statement)).all() if s]

    recent: list[str] = []
    stored = 0
    i = 0
    while stored < n and i < n * 3:
        target = _rotate_target(i, DIVERSITY_TOPICS)
        i += 1
        prompt = PROMPT.format(target=target, avoid=_avoid_block(recent))
        try:
            resp = client.complete(prompt, purpose="distill-rich", effort="high")
        except Exception as e:
            print(f"[{i}] gen error: {type(e).__name__}: {e}", flush=True)
            continue
        t = resp.text
        stmt = _tag("statement", t)
        ans = _int_answer(_tag("answer", t))
        sol = _tag("solution", t)
        if not (stmt and sol) or ans is None:
            print(f"[{i}] parse fail / answer out of range", flush=True)
            continue
        if is_banned_template(stmt) or is_garbled(stmt):
            print(f"[{i}] banned/garbled, skipped", flush=True)
            recent.append(f"[{_tag('topic', t)}] {stmt[:100]}")
            continue
        sig = token_set(stmt)
        if is_near_duplicate(sig, seen_sigs):
            print(f"[{i}] near-duplicate, skipped", flush=True)
            recent.append(f"[{_tag('topic', t)}] {stmt[:100]}")
            continue
        sh = statement_hash(stmt)
        if sh in seen:
            print(f"[{i}] duplicate, skipped", flush=True)
            continue

        topic = _tag("topic", t)
        difficulty = _num(_tag("difficulty", t), 1, 10)
        crux = _tag("crux", t) or ""
        pe = _num(_tag("problem_elegance", t), 0, 5)
        pe_reason = _tag("problem_elegance_reason", t) or ""
        se = _num(_tag("solution_elegance", t), 0, 5)
        se_reason = _tag("solution_elegance_reason", t) or ""

        seen.add(sh)
        seen_sigs.append(sig)
        recent.append(f"[{topic}] {stmt[:100]}")

        pid = f"distill-rich-{uuid.uuid4().hex[:8]}"
        with db.session_scope() as ses:
            ses.add(Problem(
                id=pid, source=ProblemSource.SYNTHETIC, statement=stmt,
                answer=str(ans), difficulty=difficulty, topic=topic,
                split=DataSplit.TRAIN, verified=None, review_status=ReviewStatus.PENDING,
                possibly_memorized=False,
                provenance={
                    "pipeline": "distill-rich", "generator_model": MODEL,
                    "thinking_effort": "high", "target": target,
                    "generated_answer": str(ans), "crux": crux,
                    "elegance": {
                        "problem": pe, "problem_reason": pe_reason,
                        "solution": se, "solution_reason": se_reason,
                        "rated_by": EVALUATOR,
                    },
                },
            ).refresh_dedup_fields())
            ses.add(Solution(problem_id=pid, text=sol, crux_insight=crux,
                             source=SolutionSource.MODEL, extractor_model=MODEL))
            if pe is not None or difficulty is not None:
                ses.add(Evaluation(
                    problem_id=pid, difficulty_score=difficulty, elegance_score=pe,
                    evaluator=EVALUATOR,
                    rationale=f"problem_elegance={pe} ({pe_reason}); solution_elegance={se} ({se_reason})"[:500]))
        stored += 1
        print(f"[{i}] STORED {pid} ans={ans} d={difficulty} PE={pe} SE={se} [{topic}] :: {stmt[:64]}", flush=True)

    print(f"done: stored {stored} rich problems", flush=True)


if __name__ == "__main__":
    main()
